import type { Player, Position, Squad, SquadPlayer } from "./types";
const BASE = "https://fantasy.premierleague.com/api";
const ttl = (name:string, fallback:number) => Number(process.env[name] ?? fallback);
const globalTags=["fpl:bootstrap","fpl:fixtures"];
const entryTag=(entryId:number)=>`fpl:entry:${entryId}`;
async function fpl(path:string,revalidate:number,tags:string[]) { const res = await fetch(`${BASE}${path}`, { next:{ revalidate,tags } }); if (!res.ok) throw new Error(`FPL request failed (${res.status})`); return res.json(); }
type Bootstrap = { elements:any[]; teams:any[]; events:any[]; element_types:any[] };
export async function bootstrap() { return fpl("/bootstrap-static/", ttl("FPL_GLOBAL_CACHE_TTL_SECONDS",7200), [globalTags[0]]) as Promise<Bootstrap>; }
export async function fixtures() { return fpl("/fixtures/", ttl("FPL_FIXTURES_CACHE_TTL_SECONDS",7200), [globalTags[1]]) as Promise<any[]>; }
export async function players():Promise<Player[]> { const [data,fixtureList]=await Promise.all([bootstrap(),fixtures()]); const positions:Record<number,Position>={1:"GKP",2:"DEF",3:"MID",4:"FWD"}; const current=data.events.find((event:any)=>event.is_current)?.id??data.events.find((event:any)=>event.is_next)?.id??1; const badge=(teamId:number)=>{const team=data.teams.find((item:any)=>item.id===teamId);return team?.code?`https://resources.premierleague.com/premierleague/badges/t${team.code}.svg`:""}; const upcoming=(teamId:number)=>fixtureList.filter((fixture:any)=>(fixture.team_h===teamId||fixture.team_a===teamId)&&!fixture.finished&&(fixture.event??current)>=current).sort((a:any,b:any)=>(a.event??999)-(b.event??999)).slice(0,5).map((fixture:any)=>{const home=fixture.team_h===teamId,opponent=home?fixture.team_a:fixture.team_h;return {opponent:data.teams.find((team:any)=>team.id===opponent)?.short_name??"",badgeUrl:badge(opponent),home,difficulty:home?fixture.team_h_difficulty:fixture.team_a_difficulty}}); return data.elements.map((p:any) => {const team=data.teams.find((item:any)=>item.id===p.team);return { id:p.id,name:`${p.first_name} ${p.second_name}`,webName:p.web_name,teamId:p.team,team:team?.short_name ?? "",badgeUrl:team?.code?`https://resources.premierleague.com/premierleague/badges/t${team.code}.svg`:"",upcomingFixtures:upcoming(p.team),position:positions[p.element_type],price:p.now_cost/10,totalPoints:p.total_points,form:Number(p.form),minutes:p.minutes,status:p.status,chance:p.chance_of_playing_next_round,news:p.news,stats:Object.fromEntries(Object.entries(p).filter(([,value])=>value===null||["string","number","boolean"].includes(typeof value))) as Record<string,string|number|boolean|null> }}); }
export function calculateFreeTransfers(history:Array<{event:number;event_transfers:number}>, currentGameweek:number, currentTransfers=0) { let available=1; for(const week of history.filter(item=>item.event<currentGameweek).sort((a,b)=>a.event-b.event)) available=Math.min(5,Math.max(1,available-week.event_transfers+1)); return Math.max(0,available-currentTransfers); }
export async function squad(entryId:number):Promise<Squad> { const entryTtl=ttl("FPL_ENTRY_CACHE_TTL_SECONDS",1800),tags=[entryTag(entryId)]; const [data,all,boot,history]=await Promise.all([fpl(`/entry/${entryId}/`,entryTtl,tags),players(),bootstrap(),fpl(`/entry/${entryId}/history/`,entryTtl,tags)]); const gw=boot.events.find((e:any)=>e.is_current)?.id ?? boot.events.find((e:any)=>e.is_next)?.id ?? 1; const pickData=await fpl(`/entry/${entryId}/event/${gw}/picks/`,entryTtl,tags); const mapped:SquadPlayer[]=pickData.picks.map((pick:any,index:number)=>({...all.find(p=>p.id===pick.element)!,purchasePrice:pick.purchase_price/10,sellingPrice:pick.selling_price/10,multiplier:pick.multiplier,isCaptain:pick.is_captain,isViceCaptain:pick.is_vice_captain,benchOrder:pick.position>11?pick.position-12:undefined})); const completed=(history.current??[]).filter((item:any)=>item.event<gw&&typeof item.points==="number"); const scores=completed.map((item:any)=>item.points); return {entryId,teamName:data.name,managerName:`${data.player_first_name} ${data.player_last_name}`,gameweek:gw,bank:pickData.entry_history?.bank != null ? pickData.entry_history.bank/10 : null,value:pickData.entry_history?.value != null ? pickData.entry_history.value/10 : null,freeTransfers:calculateFreeTransfers(history.current ?? [],gw,pickData.entry_history?.event_transfers ?? 0),lastGameweekPoints:scores.at(-1)??null,bestGameweekPoints:scores.length?Math.max(...scores):null,averageGameweekPoints:scores.length?Number((scores.reduce((total:number,points:number)=>total+points,0)/scores.length).toFixed(1)):null,players:mapped}; }
