import { bootstrap, fixtures, players } from "./fpl";
import type { Player } from "./types";

export type Operator = "equals"|"not_equals"|"greater_than"|"greater_than_or_equal"|"less_than"|"less_than_or_equal"|"in"|"not_in";
export type PlayerFilter = { field:string; operator:Operator; value:unknown };
export type PlayerQuery = { positions?:string[]; teams?:Array<number|string>; search?:string; teamSearch?:string; include_player_ids?:number[]; exclude_player_ids?:number[]; exclude_owned?:boolean; filters?:PlayerFilter[]; sort?:{field:string;direction?:"asc"|"desc"}|Array<{field:string;direction?:"asc"|"desc"}>; limit?:number };
const descriptions:Record<string,string>={now_cost:"Current FPL price in tenths of a million",total_points:"Season FPL points",form:"Recent FPL form",minutes:"Season minutes",selected_by_percent:"Ownership percentage",points_per_game:"Points per game",expected_goals:"Expected goals",expected_assists:"Expected assists",expected_goal_involvements:"Expected goal involvements",expected_goals_conceded:"Expected goals conceded",goals_conceded:"Goals conceded",clean_sheets:"Clean sheets",saves:"Saves",bonus:"Bonus points",bps:"Bonus Points System score",defensive_contribution:"Defensive contribution",influence:"FPL influence index",creativity:"FPL creativity index",threat:"FPL threat index",ict_index:"FPL ICT index"};
export function playerValue(player:Player, field:string):unknown { const aliases:Record<string,unknown>={id:player.id,name:player.name,web_name:player.webName,webName:player.webName,team:player.team,team_id:player.teamId,teamId:player.teamId,position:player.position,price:player.price,totalPoints:player.totalPoints,form:player.form,minutes:player.minutes,status:player.status,chance:player.chance}; return field in aliases?aliases[field]:player.stats[field]; }
function matches(value:unknown, operator:Operator, target:unknown) { const values=Array.isArray(target)?target:[target]; const numeric=typeof value==="number"&&typeof target==="number"; if(operator==="equals")return values.includes(value);if(operator==="not_equals")return !values.includes(value);if(operator==="in")return values.includes(value);if(operator==="not_in")return !values.includes(value);if(!numeric)return false; if(operator==="greater_than")return value>target;if(operator==="greater_than_or_equal")return value>=target;if(operator==="less_than")return value<target;return value<=target; }
export async function getPlayerStatSchema() { const list=await players();const fields=new Map<string,{name:string;type:string;description?:string}>();for(const player of list){for(const [field,value] of Object.entries({...player.stats,id:player.id,name:player.name,webName:player.webName,team:player.team,teamId:player.teamId,position:player.position,price:player.price,totalPoints:player.totalPoints,form:player.form,minutes:player.minutes,status:player.status,chance:player.chance})){if(!fields.has(field))fields.set(field,{name:field,type:value===null?"null":typeof value,description:descriptions[field]})}}return [...fields.values()].sort((a,b)=>a.name.localeCompare(b.name)); }
export async function queryPlayers(query:PlayerQuery) { let list=await players();if(query.positions?.length)list=list.filter(p=>query.positions!.includes(p.position));if(query.teams?.length)list=list.filter(p=>query.teams!.includes(p.teamId)||query.teams!.includes(p.team));if(query.search){const text=query.search.toLowerCase();list=list.filter(player=>`${player.name} ${player.webName}`.toLowerCase().includes(text))}if(query.teamSearch){const text=query.teamSearch.toLowerCase();list=list.filter(player=>player.team.toLowerCase().includes(text))}if(query.include_player_ids?.length)list=list.filter(p=>query.include_player_ids!.includes(p.id));if(query.exclude_player_ids?.length)list=list.filter(p=>!query.exclude_player_ids!.includes(p.id));for(const filter of query.filters??[])list=list.filter(player=>matches(playerValue(player,filter.field),filter.operator,filter.value));const sorts=Array.isArray(query.sort)?query.sort:query.sort?[query.sort]:[];list.sort((a,b)=>{for(const sort of sorts){const av=playerValue(a,sort.field),bv=playerValue(b,sort.field);const direction=sort.direction==="asc"?1:-1;if(typeof av==="number"&&typeof bv==="number"&&av!==bv)return (av-bv)*direction;const comparison=String(av??"").localeCompare(String(bv??""));if(comparison)return comparison*direction}return a.id-b.id});return list.slice(0,Math.min(Math.max(query.limit??20,1),100)).map(player=>({id:player.id,name:player.name,webName:player.webName,teamId:player.teamId,team:player.team,badgeUrl:player.badgeUrl,upcomingFixtures:player.upcomingFixtures,position:player.position,price:player.price,fixtureDifficulty:player.upcomingFixtures.length?player.upcomingFixtures.reduce((sum,fixture)=>sum+fixture.difficulty,0)/player.upcomingFixtures.length:null,status:player.status,chance:player.chance,stats:Object.fromEntries(["total_points","form","minutes","selected_by_percent","points_per_game","expected_goals","expected_assists","expected_goal_involvements","expected_goals_conceded","clean_sheets","goals_conceded","saves","bonus","bps","defensive_contribution"].map(field=>[field,playerValue(player,field)])),requestedFields:Object.fromEntries([...new Set([...(query.filters??[]).map(f=>f.field),...sorts.map(s=>s.field)])].map(field=>[field,playerValue(player,field)]))})); }
export async function getTeamFixtures(teamId:number, gameweeks?:number[]) { const [allFixtures,boot]=await Promise.all([fixtures(),bootstrap()]);const name=(id:number)=>boot.teams.find((team:any)=>team.id===id)?.short_name??String(id);return allFixtures.filter((fixture:any)=>(fixture.team_h===teamId||fixture.team_a===teamId)&&(!gameweeks?.length||gameweeks.includes(fixture.event))).map((fixture:any)=>{const home=fixture.team_h===teamId;return {id:fixture.id,gameweek:fixture.event,kickoff:fixture.kickoff_time,finished:fixture.finished,home,opponentId:home?fixture.team_a:fixture.team_h,opponent: name(home?fixture.team_a:fixture.team_h),difficulty:home?fixture.team_h_difficulty:fixture.team_a_difficulty,teamScore:home?fixture.team_h_score:fixture.team_a_score,opponentScore:home?fixture.team_a_score:fixture.team_h_score};}).sort((a,b)=>(a.gameweek??999)-(b.gameweek??999)); }
export async function getTeamResults(teamId:number) { const results=await getTeamFixtures(teamId);const finished=results.filter(result=>result.finished&&result.teamScore!=null&&result.opponentScore!=null);const wins=finished.filter(result=>result.teamScore!>result.opponentScore!).length,losses=finished.filter(result=>result.teamScore!<result.opponentScore!).length;return {teamId,played:finished.length,wins,draws:finished.length-wins-losses,losses,results:finished}; }
