"use client";
import { useEffect, useMemo, useState } from "react";
import type { Player, Scenario, SquadPlayer } from "@/lib/types";

type Props={scenario:Scenario|null;onCreate:()=>void;onUpdate:(update:(players:SquadPlayer[],transfers:Scenario["transfers"])=>[SquadPlayer[],Scenario["transfers"]])=>void};
const price=(player:SquadPlayer)=>player.price.toFixed(1);

export default function SquadEditor({scenario,onCreate,onUpdate}:Props){
  const [selectedId,setSelectedId]=useState<number|null>(null);const [query,setQuery]=useState("");const [club,setClub]=useState("");const [maxPrice,setMaxPrice]=useState("");const [candidates,setCandidates]=useState<Player[]>([]);const [message,setMessage]=useState("");
  const selected=useMemo(()=>scenario?.players.find(player=>player.id===selectedId)??scenario?.players[0]??null,[scenario,selectedId]);
  useEffect(()=>{if(selected)setSelectedId(selected.id)},[scenario?.id,selected?.id]);
  useEffect(()=>{if(!scenario||!selected)return;const controller=new AbortController();const ceiling=Number(maxPrice||selected.price);fetch("/api/fpl/player-query",{method:"POST",headers:{"content-type":"application/json"},signal:controller.signal,body:JSON.stringify({positions:[selected.position],exclude_player_ids:scenario.players.map(player=>player.id),filters:[{field:"now_cost",operator:"less_than_or_equal",value:Math.round(ceiling*10)}],sort:[{field:"form",direction:"desc"},{field:"total_points",direction:"desc"}],limit:12})}).then(response=>response.json()).then(data=>{if(!controller.signal.aborted)setCandidates((data.players??[]).filter((player:Player)=>!query||`${player.name} ${player.webName}`.toLowerCase().includes(query.toLowerCase())).filter((player:Player)=>!club||player.team.toLowerCase().includes(club.toLowerCase())))}).catch(()=>{});return()=>controller.abort()},[scenario,selected,query,club,maxPrice]);
  if(!scenario)return <section className="squad-editor"><p className="eyebrow">MANUAL SQUAD BUILDER</p><h3>MAKE A VERSION</h3><p>Create a private working version of your team. It never changes your real FPL squad.</p><button className="editor-primary" onClick={onCreate}>CREATE VERSION</button></section>;
  const setPlayers=(transform:(players:SquadPlayer[])=>SquadPlayer[])=>onUpdate((players,transfers)=>{const next=transform(players);return [next,transfers]});
  const replace=(incoming:Player)=>{if(!selected)return;onUpdate((players,transfers)=>[players.map(player=>player.id===selected.id?{...incoming,multiplier:player.multiplier,isCaptain:player.isCaptain,isViceCaptain:player.isViceCaptain}:player),[...transfers.filter(transfer=>transfer.out!==selected.id),{out:selected.id,in:incoming.id}]]);setMessage(`${selected.webName} → ${incoming.webName}`);setSelectedId(incoming.id)};
  const setCaptain=(vice=false)=>{if(!selected)return;setPlayers(players=>players.map(player=>vice?{...player,isViceCaptain:player.id===selected.id}:{...player,isCaptain:player.id===selected.id}));};
  return <section className="squad-editor"><p className="eyebrow">MANUAL SQUAD BUILDER</p><div className="editor-title"><h3>{scenario.label}</h3><button onClick={onCreate}>NEW VERSION</button></div><label>PLAYER TO CHANGE<select value={selected?.id??""} onChange={event=>{setSelectedId(Number(event.target.value));setMessage("")}}>{scenario.players.map(player=><option key={player.id} value={player.id}>{player.webName} · {player.position} · £{price(player)}</option>)}</select></label><div className="lineup-actions"><button onClick={()=>setPlayers(players=>players.map(player=>player.id===selected?.id?{...player,multiplier:1}:player))}>START</button><button onClick={()=>setPlayers(players=>players.map(player=>player.id===selected?.id?{...player,multiplier:0}:player))}>BENCH</button><button onClick={()=>setCaptain()}>CAPTAIN</button><button onClick={()=>setCaptain(true)}>VICE</button></div><p className="sub-note">{message?`Substitution: ${message}`:`Selected: ${selected?.webName??"—"}`}</p><div className="candidate-filters"><label>SEARCH<input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Player name"/></label><label>TEAM<input value={club} onChange={event=>setClub(event.target.value)} placeholder="e.g. ARS"/></label><label>MAX £<input value={maxPrice} onChange={event=>setMaxPrice(event.target.value)} inputMode="decimal" placeholder={selected?String(selected.price):""}/></label></div><p className="eyebrow candidates-title">REPLACEMENTS · {selected?.position}</p><div className="candidate-list">{candidates.map(player=><button key={player.id} onClick={()=>replace(player)}><span>{player.webName}<small>{player.team} · {player.position}</small></span><span>£{player.price.toFixed(1)}<small>FORM {player.form}</small></span></button>)}{!candidates.length&&<p className="micro">No candidates match these filters.</p>}</div><p className="editor-foot">You can create further working versions by resetting to Current team, then choosing Create V2.</p></section>
}
