"use client";
import { useEffect, useState } from "react";
import type { Player, Scenario, SquadPlayer } from "@/lib/types";

type Props={scenario:Scenario|null;outgoing:SquadPlayer|null;onCreate:()=>void;onReplace:(player:Player)=>void;onCancel:()=>void};
const signed=(value:number,unit="")=>(value>0?"↑":value<0?"↓":"±")+Math.abs(value).toFixed(1)+unit;
const pointsPerGame=(player:Player)=>Number(player.stats.points_per_game??0);
const fixtureAverage=(player:Player)=>player.upcomingFixtures.length?player.upcomingFixtures.reduce((sum,fixture)=>sum+fixture.difficulty,0)/player.upcomingFixtures.length:0;

export default function TransferPanel({scenario,outgoing,onCreate,onReplace,onCancel}:Props){
  const [search,setSearch]=useState("");const [team,setTeam]=useState("");const [maxPrice,setMaxPrice]=useState("");const [sort,setSort]=useState("form");const [players,setPlayers]=useState<Player[]>([]);
  useEffect(()=>{if(!scenario||!outgoing){setPlayers([]);return}const controller=new AbortController();const filters=maxPrice?[{field:"now_cost",operator:"less_than_or_equal",value:Math.round(Number(maxPrice)*10)}]:[];fetch("/api/fpl/player-query",{method:"POST",headers:{"content-type":"application/json"},signal:controller.signal,body:JSON.stringify({positions:[outgoing.position],search,teamSearch:team,exclude_player_ids:scenario.players.map(player=>player.id),filters,sort:{field:sort,direction:"desc"},limit:100})}).then(response=>response.json()).then(data=>{if(!controller.signal.aborted)setPlayers(data.players??[])}).catch(()=>{});return()=>controller.abort()},[scenario,outgoing,search,team,maxPrice,sort]);
  if(!scenario)return <section className="transfer-panel"><p className="eyebrow">TRANSFER MARKET</p><h3>BUILD A VERSION</h3><p>Create a separate draft squad. Your real team is never changed.</p><button className="editor-primary" onClick={onCreate}>CREATE VERSION</button></section>;
  if(!outgoing)return <section className="transfer-panel"><p className="eyebrow">TRANSFER MARKET · {scenario.label}</p><h3>CHOOSE A PLAYER</h3><p>Press the <b>×</b> on a player card on the pitch to find an eligible replacement.</p><button className="plain-button" onClick={onCreate}>NEW VERSION</button></section>;
  return <section className="transfer-panel"><p className="eyebrow">REPLACING</p><div className="outgoing"><strong>{outgoing.webName}</strong><span>{outgoing.team} · {outgoing.position} · £{outgoing.price.toFixed(1)}m</span><button onClick={onCancel}>CANCEL</button></div><div className="market-filters"><label>SEARCH<input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search by name"/></label><label>TEAM<input value={team} onChange={event=>setTeam(event.target.value)} placeholder="Any team"/></label><label>MAX PRICE<input value={maxPrice} onChange={event=>setMaxPrice(event.target.value)} inputMode="decimal" placeholder="No limit"/></label><label>SORT<select value={sort} onChange={event=>setSort(event.target.value)}><option value="form">Form</option><option value="total_points">Total points</option><option value="minutes">Minutes</option><option value="selected_by_percent">Ownership</option></select></label></div><p className="eyebrow candidates-title">{players.length} {outgoing.position} OPTIONS</p><div className="candidate-list">{players.map(player=>{const priceDelta=player.price-outgoing.price,ppgDelta=pointsPerGame(player)-pointsPerGame(outgoing);return <button key={player.id} onClick={()=>onReplace(player)}><span className="candidate-identity">{player.badgeUrl&&<img src={player.badgeUrl} alt="" />}<span><strong>{player.webName}</strong><small>{player.position}</small></span></span><span>£{player.price.toFixed(1)}m<small className={priceDelta>0?"delta bad":"delta good"}>{signed(priceDelta,"m")} {priceDelta>0?"more":"less"}</small><small className={ppgDelta>=0?"delta good":"delta bad"}>{signed(ppgDelta)} PPG</small></span><b>↑</b></button>})}{!players.length&&<p className="micro">No available players match these filters.</p>}</div></section>;
}
